### ISSUE TITLE
Story - Starting from a Blank State

### ISSUE THREAD

**Issue by SkylerBurger** [SkylerBurger/new_tab_dialer#1]
As a new user, I want to begin using and customizing the extension without loading a configuration file.

Required Tasks:
- [X] Add a Group (#8)
- [X] Delete a Group (#7)
- [X] Rename a Group (#47)
- [X] Modify Group Tab order (#42)
- [X] Add a Dial to a Group (#19)
- [X] Delete a Dial from a Group (#23)
- [X] Transfer a Dial to another Group (#24)
- [x] Modify a Dial (#46)
- [X] Reorder Dials within a Group Tab (#22)
- [x] Landing Page (#53)
- [x] Export Current Config to file (#15)

**Comment by SkylerBurger** [comment]
All Issues that keep a user from starting with the extension from scratch have been resolved!
